name: Test and Coverage for Purchase Order
on:
  push:
    branches:
      - pre-prod
  pull_request:
concurrency:
  group: purchase-order-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Run Tests for Purchase Order
    services:
      redis-cache:
        image: redis:alpine
        ports:
          - 13000:6379
      redis-queue:
        image: redis:alpine
        ports:
          - 11000:6379
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mariadb-admin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true

      - name: Cache pip Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/pyproject.toml', '**/setup.py', '**/setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Install MariaDB Client and Redis Server
        run: sudo apt-get install -y mariadb-client mariadb-server redis-server

      - name: Setup Frappe Bench
        run: |
          pip install frappe-bench
          bench init --skip-redis-config-generation --skip-assets --python "$(which python)" ~/frappe-bench
          mariadb --host 127.0.0.1 --port 3306 -u root -proot -e "SET GLOBAL character_set_server = 'utf8mb4'"
          mariadb --host 127.0.0.1 --port 3306 -u root -proot -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"

      - name: Install ERPNext
        working-directory: /home/runner/frappe-bench
        run: |
          bench get-app erpnext https://github.com/tinadn/erpnext.git --branch develop
          bench setup requirements --dev
          bench new-site --db-root-password root --admin-password admin test_site
          bench --site test_site install-app erpnext
        env:
          CI: 'Yes'

      - name: Run Tests for Purchase Order
        working-directory: /home/runner/frappe-bench
        run: |
          bench --site test_site set-config allow_tests true
          bench --site test_site run-tests --doctype "Purchase Order"
        env:
          TYPE: server

      - name: Run Coverage for Purchase Order
        working-directory: /home/runner/frappe-bench/apps/erpnext
        run: |
          pip install pytest pytest-cov
          pytest --cov=erpnext/erpnext/buying/doctype/purchase_order \
                 --cov-report=term-missing \
                 --cov-report=xml \
                 --cov-fail-under=80 \
                 tests/erpnext/buying/doctype/purchase_order/test_purchase_order.py

      - name: Upload Coverage Report
        uses: acid-chicken/lcov-reporter-action@v0.4.1
        with:
          coverage_file: frappe-bench/apps/erpnext/coverage.xml
          minimum_coverage: 80
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
