name: PO
on:
  push:
    branches:
      - pre-prod
  pull_request:
concurrency:
  group: test-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      redis-cache:
        image: redis:alpine
        ports:
          - 13000:6379
      redis-queue:
        image: redis:alpine
        ports:
          - 11000:6379
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mariadb-admin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-client mariadb-server redis-server
          pip install frappe-bench pytest pytest-cov

      - name: Setup Frappe Bench
        run: |
          sudo pip3 install frappe-bench
          bench init --frappe-branch version-15 frappe-bench
          mariadb --host 127.0.0.1 --port 3306 -u root -proot -e "SET GLOBAL character_set_server = 'utf8mb4'"
          mariadb --host 127.0.0.1 --port 3306 -u root -proot -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"
        env:
          PATH: ${{ github.workspace }}:$PATH

      - name: Install ERPNext
        working-directory: /home/runner/frappe-bench
        run: |
          bench get-app erpnext https://github.com/tinadn/erpnext.git --branch version-15
          bench setup requirements --dev
          bench new-site --db-root-password root --admin-password admin test_site
          bench --site test_site install-app erpnext
        env:
          CI: 'Yes'

      - name: Run Frappe Tests Only
        working-directory: /home/runner/frappe-bench/apps/erpnext
        run: |
          bench --site test_site set-config allow_tests true
          pytest --cov=erpnext --cov-report=term-missing --cov-report=xml erpnext --ignore-glob="!**/test_*.py"
        env:
          TYPE: server

      - name: Upload Coverage Report
        uses: acid-chicken/lcov-reporter-action@v0.4.1
        with:
          coverage_file: /home/runner/frappe-bench/apps/erpnext/coverage.xml
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
